// app/desktop/src/lib/components/MetaModelPanel.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { MetaModelState } from '$lib/stores/metamodel';
  import { metaModelStore } from '$lib/stores/metamodel';

  let state: MetaModelState = { status: 'idle', schema: null, error: null };

  const unsubscribe = metaModelStore.subscribe((value) => {
    state = value;
  });

  async function loadMetaModel() {
    try {
      await metaModelStore.load();
    } catch {
      // store already captures the error state; nothing else needed here.
    }
  }

  async function refreshMetaModel() {
    try {
      await metaModelStore.refresh();
    } catch {
      // handled by the store state
    }
  }

  onMount(() => {
    loadMetaModel();
    return unsubscribe;
  });

  const toTitle = (value: string | undefined, fallback: string) => value ?? fallback;
</script>

<section class="meta-panel">
  <header>
    <div>
      <h1>Schema Reference</h1>
      {#if state.schema?.description}
        <p class="muted">{state.schema.description}</p>
      {/if}
    </div>
    <div class="status">
      <span class="pill">Version · {state.schema?.version ?? 'loading'}</span>
      {#if state.status === 'loading'}
        <span class="pill info">Loading…</span>
      {:else if state.status === 'error'}
        <span class="pill warning">Error</span>
      {:else if state.status === 'ready'}
        <span class="pill success">Live</span>
      {/if}
    </div>
  </header>

  {#if state.status === 'error'}
    <div class="alert">
      <h2>Failed to load meta-model</h2>
      <p>{state.error}</p>
      <button type="button" class="retry" on:click={refreshMetaModel}>Retry</button>
    </div>
  {:else if state.status === 'loading' && !state.schema}
    <p class="muted">Fetching schema…</p>
  {:else if !state.schema}
    <p class="muted">Schema not available yet.</p>
  {:else}
    <div class="summary">
      <article>
        <h3>Types</h3>
        <p class="count">{state.schema.types.length}</p>
        <p class="muted">Element definitions available to the worker.</p>
      </article>
      <article>
        <h3>Relationships</h3>
        <p class="count">{state.schema.relationships.length}</p>
        <p class="muted">Allowed links between element types.</p>
      </article>
    </div>

    <section class="grid">
      <div>
        <h2>Element Types</h2>
        <ul class="card-list">
          {#each state.schema.types as type (type.id)}
            <li class="card">
              <div class="card__header">
                <div>
                  <h3>{toTitle(type.label, type.id)}</h3>
                  <p class="muted">{type.category ?? 'Uncategorised'}</p>
                </div>
                {#if type.extends}
                  <span class="pill">Extends {type.extends}</span>
                {/if}
              </div>
              {#if type.attributes?.length}
                <dl>
                  {#each type.attributes as attribute (attribute.name)}
                    <div>
                      <dt>
                        {attribute.name}
                        {#if attribute.required}
                          <span class="required">required</span>
                        {/if}
                      </dt>
                      <dd>
                        {attribute.type}
                        {#if attribute.enum?.length}
                          <span class="muted">[{attribute.enum.join(', ')}]</span>
                        {/if}
                      </dd>
                    </div>
                  {/each}
                </dl>
              {:else}
                <p class="muted">No attributes defined.</p>
              {/if}
            </li>
          {/each}
        </ul>
      </div>
      <div>
        <h2>Relationships</h2>
        <ul class="card-list">
          {#each state.schema.relationships as rel (rel.id)}
            <li class="card">
              <div class="card__header">
                <div>
                  <h3>{toTitle(rel.label, rel.id)}</h3>
                  <p class="muted">{rel.directed === false ? 'Undirected' : 'Directed'}</p>
                </div>
              </div>
              <p class="muted">{rel.from.join(', ')} → {rel.to.join(', ')}</p>
              {#if rel.attributes?.length}
                <dl>
                  {#each rel.attributes as attribute (attribute.name)}
                    <div>
                      <dt>{attribute.name}</dt>
                      <dd>
                        {attribute.type}
                        {#if attribute.enum?.length}
                          <span class="muted">[{attribute.enum.join(', ')}]</span>
                        {/if}
                      </dd>
                    </div>
                  {/each}
                </dl>
              {/if}
            </li>
          {/each}
        </ul>
      </div>
    </section>
  {/if}
</section>

<style>
  .meta-panel {
    padding: 24px;
    display: flex;
    flex-direction: column;
    gap: 24px;
  }
  header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
  }
  .status {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }
  .pill {
    border-radius: 999px;
    padding: 6px 12px;
    font-size: 0.85rem;
    background: color-mix(in srgb, var(--color-border) 65%, transparent);
  }
  .pill.info {
    background: color-mix(in srgb, var(--color-accent) 25%, transparent);
  }
  .pill.success {
    background: color-mix(in srgb, #10b981 30%, transparent);
  }
  .pill.warning {
    background: color-mix(in srgb, #f97316 25%, transparent);
  }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 16px;
  }
  .summary article {
    border: 1px solid var(--color-border);
    border-radius: 16px;
    padding: 16px;
    background: color-mix(in srgb, var(--color-surface) 85%, transparent);
  }
  .summary .count {
    font-size: 2rem;
    margin: 4px 0;
  }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 24px;
  }
  .card-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 16px;
  }
  .card {
    border: 1px solid var(--color-border);
    border-radius: 18px;
    padding: 16px;
    background: color-mix(in srgb, var(--color-surface) 92%, transparent);
    box-shadow: 0 12px 24px -20px rgba(15, 23, 42, 0.45);
  }
  .card__header {
    display: flex;
    justify-content: space-between;
    gap: 8px;
    margin-bottom: 12px;
  }
  dl {
    margin: 0;
    display: grid;
    gap: 4px;
  }
  dt {
    font-weight: 600;
  }
  dd {
    margin: 0;
    color: color-mix(in srgb, var(--color-text) 80%, transparent);
  }
  .muted {
    color: color-mix(in srgb, var(--color-text) 70%, transparent);
    margin: 0;
  }
  .required {
    margin-left: 6px;
    font-size: 0.75rem;
    color: #dc2626;
  }
  .alert {
    border: 1px solid color-mix(in srgb, #f97316 45%, transparent);
    border-radius: 12px;
    padding: 16px;
    background: color-mix(in srgb, #fff7ed 85%, transparent);
  }
  .retry {
    margin-top: 12px;
    border: none;
    background: color-mix(in srgb, var(--color-accent) 35%, transparent);
    color: #fff;
    border-radius: 999px;
    padding: 6px 14px;
    cursor: pointer;
  }
</style>

// app/AideonDesktop/src/canvas/components/dashboard/meta-model-panel.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';

import { fetchMetaModel, type MetaModelSchema } from 'canvas/lib/meta-model';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '../../../design-system/components/ui/accordion';
import { Badge } from '../../../design-system/components/ui/badge';
import { Button } from '../../../design-system/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '../../../design-system/components/ui/card';

type Status = 'idle' | 'loading' | 'ready' | 'error';

interface MetaModelPanelProperties {
  readonly focusEntryId?: string;
}

export function MetaModelPanel({ focusEntryId }: MetaModelPanelProperties = {}) {
  const [status, setStatus] = useState<Status>('idle');
  const [schema, setSchema] = useState<MetaModelSchema | null>(null);
  const [error, setError] = useState<string | null>(null);

  const loadSchema = useCallback(async () => {
    setStatus('loading');
    setError(null);
    try {
      const result = await fetchMetaModel();
      setSchema(result);
      setStatus('ready');
    } catch (unknownError) {
      const message = unknownError instanceof Error ? unknownError.message : String(unknownError);
      setError(message);
      setStatus('error');
    }
  }, []);

  useEffect(() => {
    void loadSchema();
  }, [loadSchema]);

  return (
    <Card>
      <CardHeader className="space-y-1">
        <CardTitle>Meta-model inspector</CardTitle>
        <CardDescription>
          {schema?.description ?? 'Schema reference for types and relationships.'}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
          <Badge variant="secondary">Version · {schema?.version ?? 'loading'}</Badge>
          <Badge variant="outline">{status === 'ready' ? 'Live' : status}</Badge>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              void loadSchema();
            }}
            disabled={status === 'loading'}
          >
            Reload schema
          </Button>
        </div>
        {renderSchemaState({
          status,
          schema,
          error,
          focusEntryId,
          onRetry: () => {
            void loadSchema();
          },
        })}
      </CardContent>
    </Card>
  );
}

const renderSchemaState = ({
  status,
  schema,
  error,
  focusEntryId,
  onRetry,
}: {
  readonly status: Status;
  readonly schema: MetaModelSchema | null;
  readonly error: string | null;
  readonly focusEntryId?: string;
  readonly onRetry: () => void;
}) => {
  if (status === 'error') {
    return (
      <div className="rounded-2xl border border-destructive/40 bg-destructive/5 p-4 text-xs">
        <p className="font-semibold text-destructive">Failed to load meta-model</p>
        <p className="text-destructive/80">{error}</p>
        <Button variant="outline" size="sm" className="mt-3" onClick={onRetry}>
          Retry load
        </Button>
      </div>
    );
  }
  if (status === 'loading' && !schema) {
    return <p className="text-xs text-muted-foreground">Fetching schema…</p>;
  }
  if (!schema) {
    return <p className="text-xs text-muted-foreground">Schema not available yet.</p>;
  }
  return <SchemaDetails schema={schema} focusEntryId={focusEntryId} />;
};

function SchemaDetails({
  schema,
  focusEntryId,
}: {
  readonly schema: MetaModelSchema;
  readonly focusEntryId?: string;
}) {
  useEffect(() => {
    if (!focusEntryId) {
      return;
    }
    const element = document.querySelector<HTMLElement>(`[data-metamodel-entry="${focusEntryId}"]`);
    element?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, [focusEntryId, schema]);

  const focusedIds = useMemo(
    () => new Set([focusEntryId].filter(Boolean) as string[]),
    [focusEntryId],
  );

  return (
    <div className="space-y-6">
      <div className="grid gap-4 rounded-2xl border border-border/60 bg-muted/10 p-4 text-center text-sm">
        <StatBlock label="Types" value={schema.types.length} />
        <StatBlock label="Relationships" value={schema.relationships.length} />
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <Accordion defaultValue="types" type="single" collapsible>
          <AccordionItem value="types">
            <AccordionTrigger className="text-sm font-semibold">Types</AccordionTrigger>
            <AccordionContent>
              <div className="flex flex-col gap-3">
                {schema.types.map((type) => (
                  <MetaModelEntryCard
                    key={type.id}
                    id={type.id}
                    label={type.label ?? type.id}
                    description={type.category ?? 'Type'}
                    extra={type.extends ? `extends ${type.extends}` : undefined}
                    focused={focusedIds.has(type.id)}
                  >
                    <AttributesList attributes={type.attributes} />
                  </MetaModelEntryCard>
                ))}
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
        <Accordion defaultValue="relationships" type="single" collapsible>
          <AccordionItem value="relationships">
            <AccordionTrigger className="text-sm font-semibold">Relationships</AccordionTrigger>
            <AccordionContent>
              <div className="flex flex-col gap-3">
                {schema.relationships.map((relationship) => (
                  <MetaModelEntryCard
                    key={relationship.id}
                    id={relationship.id}
                    label={relationship.label ?? relationship.id}
                    description={`${relationship.from.join(', ')} → ${relationship.to.join(', ')}`}
                    extra={relationship.directed === false ? 'Undirected' : 'Directed'}
                    focused={focusedIds.has(relationship.id)}
                  >
                    <AttributesList attributes={relationship.attributes} />
                  </MetaModelEntryCard>
                ))}
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}

function StatBlock({ label, value }: { readonly label: string; readonly value: number }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">{label}</p>
      <p className="text-2xl font-semibold">{value}</p>
    </div>
  );
}

function MetaModelEntryCard({
  id,
  label,
  description,
  extra,
  focused,
  children,
}: {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly extra?: string;
  readonly focused: boolean;
  readonly children: React.ReactNode;
}) {
  return (
    <article
      data-metamodel-entry={id}
      className={`rounded-2xl border p-4 transition ${
        focused ? 'border-primary/60 bg-primary/5 shadow-inner' : 'border-border/60 bg-card'
      }`}
    >
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="text-sm font-semibold">{label}</p>
          <p className="text-xs text-muted-foreground">{description}</p>
        </div>
        {extra ? (
          <Badge variant="secondary" className="text-[0.6rem] uppercase tracking-[0.3em]">
            {extra}
          </Badge>
        ) : null}
      </div>
      {children}
    </article>
  );
}

function AttributesList({
  attributes,
}: {
  readonly attributes?: MetaModelSchema['types'][number]['attributes'];
}) {
  if (!attributes || attributes.length === 0) {
    return <p className="pt-2 text-xs text-muted-foreground">No attributes defined.</p>;
  }
  return (
    <dl className="mt-2 space-y-2 text-xs">
      {attributes.map((attribute) => (
        <div key={attribute.name} className="flex justify-between gap-2">
          <dt className="font-medium">
            {attribute.name}
            {attribute.required ? (
              <span className="ml-2 rounded-full bg-destructive/10 px-2 py-0.5 text-[0.65rem] text-destructive">
                required
              </span>
            ) : null}
          </dt>
          <dd className="text-muted-foreground">
            {attribute.type}
            {attribute.enum?.length ? ` [${attribute.enum.join(', ')}]` : ''}
          </dd>
        </div>
      ))}
    </dl>
  );
}
