// app/desktop/src/lib/ui/Button.svelte
<script lang="ts">
  type Variant = 'primary' | 'secondary' | 'ghost' | 'danger';
  type Size = 'sm' | 'md' | 'lg';
  const {
    variant = 'secondary',
    size = 'md',
    disabled = false,
    type = 'button',
  } = $props<{
    variant?: Variant;
    size?: Size;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
  }>();
</script>

<button class={'btn ' + variant + ' ' + size} {disabled} {type}>
  <span class="content"><slot /></span>
  <slot name="end"></slot>
  <slot name="badge"></slot>
  <span class="focus-ring"></span>
</button>

<style>
  .btn {
    --h: 32px;
    height: var(--h);
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    border-radius: var(--radius-1);
    border: 1px solid var(--color-border);
    background: var(--color-bg);
    color: var(--color-text);
    padding: 0 var(--space-3);
    box-shadow: none;
  }
  .btn.sm {
    --h: 28px;
    padding: 0 var(--space-2);
  }
  .btn.lg {
    --h: 40px;
    padding: 0 var(--space-4);
  }

  .btn.primary {
    background: var(--color-accent);
    border-color: color-mix(in srgb, var(--color-accent) 60%, var(--color-border));
    color: #fff;
  }
  .btn.danger {
    background: color-mix(in srgb, var(--color-danger) 90%, #0000);
    border-color: color-mix(in srgb, var(--color-danger) 60%, var(--color-border));
    color: #fff;
  }
  .btn.ghost {
    background: transparent;
  }
  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .btn:focus-visible {
    outline: none;
    position: relative;
  }
  .btn .focus-ring {
    pointer-events: none;
    position: absolute;
    inset: -3px;
    border-radius: calc(var(--radius-1) + 2px);
    border: 2px solid color-mix(in srgb, var(--color-accent) 70%, transparent);
    opacity: 0;
  }
  .btn:focus-visible .focus-ring {
    opacity: 1;
  }
</style>

// app/AideonDesktop/src/design-system/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "design-system/lib/utilities"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        icon: "size-9",
        "icon-sm": "size-8",
        "icon-lg": "size-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot : "button"

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
