// packages/app/src/renderer/Settings.svelte
<script lang="ts">
  import './theme.css';
  type ThemeMode = 'system' | 'light' | 'dark';
  let mode: ThemeMode = (localStorage.getItem('themeMode') as ThemeMode) || 'system';

  function apply(mode_: ThemeMode) {
    document.body.classList.remove('theme-light', 'theme-dark');
    if (mode_ === 'light') document.body.classList.add('theme-light');
    else if (mode_ === 'dark') document.body.classList.add('theme-dark');
  }

  function setMode(next: ThemeMode) {
    mode = next;
    localStorage.setItem('themeMode', mode);
    apply(mode);
  }

  apply(mode);
</script>

<div style="padding:16px; font-family: var(--font-ui); min-width: 480px;">
  <h2 style="margin:0 0 12px 0;">Appearance</h2>
  <fieldset style="border: none; padding: 0;">
    <legend style="margin-bottom: 8px;">Theme</legend>
    <label
      ><input
        type="radio"
        name="mode"
        value="system"
        bind:group={mode}
        on:change={() => setMode('system')}
      /> System</label
    >
    <label style="margin-left:12px"
      ><input
        type="radio"
        name="mode"
        value="light"
        bind:group={mode}
        on:change={() => setMode('light')}
      /> Light</label
    >
    <label style="margin-left:12px"
      ><input
        type="radio"
        name="mode"
        value="dark"
        bind:group={mode}
        on:change={() => setMode('dark')}
      /> Dark</label
    >
  </fieldset>
  <p style="opacity:0.75; margin-top:12px;">Accent color follows system (AccentColor).</p>
</div>

<style>
  :global(.theme-light) {
    color-scheme: light;
  }
  :global(.theme-dark) {
    color-scheme: dark;
  }
</style>

// app/PraxisCanvas/src/windows/settings.tsx
import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';

import './settings-window.css';

type ThemeMode = 'system' | 'light' | 'dark';

function applyTheme(mode: ThemeMode) {
  const body = document.body;
  body.classList.remove('theme-light', 'theme-dark');
  if (mode === 'light') {
    body.classList.add('theme-light');
  } else if (mode === 'dark') {
    body.classList.add('theme-dark');
  }
}

function SettingsWindow() {
  const [mode, setMode] = useState<ThemeMode>(() => {
    if (typeof window === 'undefined') {
      return 'system';
    }
    const stored = window.localStorage.getItem('themeMode') as ThemeMode | null;
    return stored ?? 'system';
  });

  useEffect(() => {
    applyTheme(mode);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('themeMode', mode);
    }
  }, [mode]);

  return (
    <div className="settings-shell">
      <h2>Appearance</h2>
      <fieldset>
        <legend style={{ marginBottom: 8 }}>Theme</legend>
        <label>
          <input
            type="radio"
            name="mode"
            value="system"
            checked={mode === 'system'}
            onChange={() => setMode('system')}
          />
          System
        </label>
        <label>
          <input
            type="radio"
            name="mode"
            value="light"
            checked={mode === 'light'}
            onChange={() => setMode('light')}
          />
          Light
        </label>
        <label>
          <input
            type="radio"
            name="mode"
            value="dark"
            checked={mode === 'dark'}
            onChange={() => setMode('dark')}
          />
          Dark
        </label>
      </fieldset>
      <p className="helper">Accent color follows system (AccentColor).</p>
    </div>
  );
}

const settingsRoot = document.getElementById('root');
if (settingsRoot) {
  createRoot(settingsRoot).render(<SettingsWindow />);
}
