// app/PraxisCanvas/src/components/ui/button.tsx
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';

import { cn } from '@/lib/utilities';

const buttonVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 ring-offset-background',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground shadow hover:bg-primary/90',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        outline:
          'border border-input bg-background hover:bg-accent/50 hover:text-accent-foreground',
        ghost: 'hover:bg-accent/40 hover:text-accent-foreground',
        muted: 'bg-muted text-muted-foreground hover:text-foreground',
      },
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8',
        icon: 'h-10 w-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  },
);

interface ButtonProperties
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProperties>(
  ({ className, variant, size, asChild = false, ...properties }, reference) => {
    const Comp = asChild ? Slot : 'button';
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={reference}
        {...properties}
      />
    );
  },
);

Button.displayName = 'Button';

export { Button, buttonVariants };

// app/desktop/src/lib/ui/Button.svelte
<script lang="ts">
  type Variant = 'primary' | 'secondary' | 'ghost' | 'danger';
  type Size = 'sm' | 'md' | 'lg';
  const {
    variant = 'secondary',
    size = 'md',
    disabled = false,
    type = 'button',
  } = $props<{
    variant?: Variant;
    size?: Size;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
  }>();
</script>

<button class={'btn ' + variant + ' ' + size} {disabled} {type}>
  <span class="content"><slot /></span>
  <slot name="end"></slot>
  <slot name="badge"></slot>
  <span class="focus-ring"></span>
</button>

<style>
  .btn {
    --h: 32px;
    height: var(--h);
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    border-radius: var(--radius-1);
    border: 1px solid var(--color-border);
    background: var(--color-bg);
    color: var(--color-text);
    padding: 0 var(--space-3);
    box-shadow: none;
  }
  .btn.sm {
    --h: 28px;
    padding: 0 var(--space-2);
  }
  .btn.lg {
    --h: 40px;
    padding: 0 var(--space-4);
  }

  .btn.primary {
    background: var(--color-accent);
    border-color: color-mix(in srgb, var(--color-accent) 60%, var(--color-border));
    color: #fff;
  }
  .btn.danger {
    background: color-mix(in srgb, var(--color-danger) 90%, #0000);
    border-color: color-mix(in srgb, var(--color-danger) 60%, var(--color-border));
    color: #fff;
  }
  .btn.ghost {
    background: transparent;
  }
  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .btn:focus-visible {
    outline: none;
    position: relative;
  }
  .btn .focus-ring {
    pointer-events: none;
    position: absolute;
    inset: -3px;
    border-radius: calc(var(--radius-1) + 2px);
    border: 2px solid color-mix(in srgb, var(--color-accent) 70%, transparent);
    opacity: 0;
  }
  .btn:focus-visible .focus-ring {
    opacity: 1;
  }
</style>
