// app/PraxisCanvas/src/components/dashboard/meta-model-panel.tsx
import { useCallback, useEffect, useState } from 'react';

import { fetchMetaModel, type MetaModelSchema } from '@/lib/meta-model';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

type Status = 'idle' | 'loading' | 'ready' | 'error';

export function MetaModelPanel() {
  const [status, setStatus] = useState<Status>('idle');
  const [schema, setSchema] = useState<MetaModelSchema | null>(null);
  const [error, setError] = useState<string | null>(null);

  const loadSchema = useCallback(async () => {
    setStatus('loading');
    setError(null);
    try {
      const result = await fetchMetaModel();
      setSchema(result);
      setStatus('ready');
    } catch (unknownError) {
      const message = unknownError instanceof Error ? unknownError.message : String(unknownError);
      setError(message);
      setStatus('error');
    }
  }, []);

  useEffect(() => {
    void loadSchema();
  }, [loadSchema]);

  return (
    <Card>
      <CardHeader className="space-y-1">
        <CardTitle>Schema reference</CardTitle>
        <CardDescription>
          {schema?.description ?? 'Meta-model entities and relationship definitions.'}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4 text-sm">
        <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
          <span className="rounded-full border border-border/70 px-3 py-1 font-medium">
            Version · {schema?.version ?? 'loading'}
          </span>
          <span className="rounded-full border border-border/70 px-3 py-1 font-medium">
            Status · {status === 'ready' ? 'live' : status}
          </span>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              void loadSchema();
            }}
            disabled={status === 'loading'}
          >
            Refresh
          </Button>
        </div>
        {renderSchemaState({
          status,
          schema,
          error,
          onRetry: () => {
            void loadSchema();
          },
        })}
      </CardContent>
    </Card>
  );
}

function renderSchemaState(parameters: {
  readonly status: Status;
  readonly schema: MetaModelSchema | null;
  readonly error: string | null;
  readonly onRetry: () => void;
}) {
  const { status, schema, error, onRetry } = parameters;
  if (status === 'error') {
    return (
      <div className="rounded-2xl border border-destructive/40 bg-destructive/5 p-4 text-xs">
        <p className="font-semibold text-destructive">Failed to load meta-model</p>
        <p className="text-destructive/80">{error}</p>
        <Button
          variant="outline"
          size="sm"
          className="mt-3"
          onClick={() => {
            onRetry();
          }}
        >
          Retry
        </Button>
      </div>
    );
  }
  if (status === 'loading' && !schema) {
    return <p className="text-xs text-muted-foreground">Fetching schema…</p>;
  }
  if (!schema) {
    return <p className="text-xs text-muted-foreground">Schema not available yet.</p>;
  }
  return <SchemaDetails schema={schema} />;
}

function SchemaDetails({ schema }: { readonly schema: MetaModelSchema }) {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3 rounded-2xl border border-border/60 bg-muted/10 p-4 text-center text-sm">
        <div>
          <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">Types</p>
          <p className="text-2xl font-semibold">{schema.types.length}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">Relationships</p>
          <p className="text-2xl font-semibold">{schema.relationships.length}</p>
        </div>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <ul className="space-y-3">
          {schema.types.map((type) => (
            <li key={type.id} className="rounded-2xl border border-border/60 p-3">
              <p className="text-sm font-semibold">{type.label ?? type.id}</p>
              <p className="text-xs text-muted-foreground">{type.category ?? 'Uncategorised'}</p>
              {type.extends ? (
                <p className="text-xs text-muted-foreground">Extends {type.extends}</p>
              ) : null}
              <AttributesList attributes={type.attributes} />
            </li>
          ))}
        </ul>
        <ul className="space-y-3">
          {schema.relationships.map((relationship) => (
            <li key={relationship.id} className="rounded-2xl border border-border/60 p-3">
              <p className="text-sm font-semibold">{relationship.label ?? relationship.id}</p>
              <p className="text-xs text-muted-foreground">
                {relationship.from.join(', ')} → {relationship.to.join(', ')} ·{' '}
                {relationship.directed === false ? 'Undirected' : 'Directed'}
              </p>
              <AttributesList attributes={relationship.attributes} />
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function AttributesList({
  attributes,
}: {
  readonly attributes?: MetaModelSchema['types'][number]['attributes'];
}) {
  if (!attributes || attributes.length === 0) {
    return <p className="text-xs text-muted-foreground">No attributes defined.</p>;
  }
  return (
    <dl className="mt-2 space-y-2 text-xs">
      {attributes.map((attribute) => (
        <div key={attribute.name} className="flex justify-between gap-2">
          <dt className="font-medium">
            {attribute.name}
            {attribute.required ? (
              <span className="ml-2 rounded-full bg-destructive/10 px-2 py-0.5 text-[0.65rem] text-destructive">
                required
              </span>
            ) : null}
          </dt>
          <dd className="text-muted-foreground">
            {attribute.type}
            {attribute.enum?.length ? ` [${attribute.enum.join(', ')}]` : ''}
          </dd>
        </div>
      ))}
    </dl>
  );
}

// app/desktop/src/lib/components/MetaModelPanel.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { MetaModelState } from '$lib/stores/metamodel';
  import { metaModelStore } from '$lib/stores/metamodel';

  let state: MetaModelState = { status: 'idle', schema: null, error: null };

  const unsubscribe = metaModelStore.subscribe((value) => {
    state = value;
  });

  async function loadMetaModel() {
    try {
      await metaModelStore.load();
    } catch {
      // store already captures the error state; nothing else needed here.
    }
  }

  async function refreshMetaModel() {
    try {
      await metaModelStore.refresh();
    } catch {
      // handled by the store state
    }
  }

  onMount(() => {
    loadMetaModel();
    return unsubscribe;
  });

  const toTitle = (value: string | undefined, fallback: string) => value ?? fallback;
</script>

<section class="meta-panel">
  <header>
    <div>
      <h1>Schema Reference</h1>
      {#if state.schema?.description}
        <p class="muted">{state.schema.description}</p>
      {/if}
    </div>
    <div class="status">
      <span class="pill">Version · {state.schema?.version ?? 'loading'}</span>
      {#if state.status === 'loading'}
        <span class="pill info">Loading…</span>
      {:else if state.status === 'error'}
        <span class="pill warning">Error</span>
      {:else if state.status === 'ready'}
        <span class="pill success">Live</span>
      {/if}
    </div>
  </header>

  {#if state.status === 'error'}
    <div class="alert">
      <h2>Failed to load meta-model</h2>
      <p>{state.error}</p>
      <button type="button" class="retry" on:click={refreshMetaModel}>Retry</button>
    </div>
  {:else if state.status === 'loading' && !state.schema}
    <p class="muted">Fetching schema…</p>
  {:else if !state.schema}
    <p class="muted">Schema not available yet.</p>
  {:else}
    <div class="summary">
      <article>
        <h3>Types</h3>
        <p class="count">{state.schema.types.length}</p>
        <p class="muted">Element definitions available to the worker.</p>
      </article>
      <article>
        <h3>Relationships</h3>
        <p class="count">{state.schema.relationships.length}</p>
        <p class="muted">Allowed links between element types.</p>
      </article>
    </div>

    <section class="grid">
      <div>
        <h2>Element Types</h2>
        <ul class="card-list">
          {#each state.schema.types as type (type.id)}
            <li class="card">
              <div class="card__header">
                <div>
                  <h3>{toTitle(type.label, type.id)}</h3>
                  <p class="muted">{type.category ?? 'Uncategorised'}</p>
                </div>
                {#if type.extends}
                  <span class="pill">Extends {type.extends}</span>
                {/if}
              </div>
              {#if type.attributes?.length}
                <dl>
                  {#each type.attributes as attribute (attribute.name)}
                    <div>
                      <dt>
                        {attribute.name}
                        {#if attribute.required}
                          <span class="required">required</span>
                        {/if}
                      </dt>
                      <dd>
                        {attribute.type}
                        {#if attribute.enum?.length}
                          <span class="muted">[{attribute.enum.join(', ')}]</span>
                        {/if}
                      </dd>
                    </div>
                  {/each}
                </dl>
              {:else}
                <p class="muted">No attributes defined.</p>
              {/if}
            </li>
          {/each}
        </ul>
      </div>
      <div>
        <h2>Relationships</h2>
        <ul class="card-list">
          {#each state.schema.relationships as rel (rel.id)}
            <li class="card">
              <div class="card__header">
                <div>
                  <h3>{toTitle(rel.label, rel.id)}</h3>
                  <p class="muted">{rel.directed === false ? 'Undirected' : 'Directed'}</p>
                </div>
              </div>
              <p class="muted">{rel.from.join(', ')} → {rel.to.join(', ')}</p>
              {#if rel.attributes?.length}
                <dl>
                  {#each rel.attributes as attribute (attribute.name)}
                    <div>
                      <dt>{attribute.name}</dt>
                      <dd>
                        {attribute.type}
                        {#if attribute.enum?.length}
                          <span class="muted">[{attribute.enum.join(', ')}]</span>
                        {/if}
                      </dd>
                    </div>
                  {/each}
                </dl>
              {/if}
            </li>
          {/each}
        </ul>
      </div>
    </section>
  {/if}
</section>

<style>
  .meta-panel {
    padding: 24px;
    display: flex;
    flex-direction: column;
    gap: 24px;
  }
  header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
  }
  .status {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }
  .pill {
    border-radius: 999px;
    padding: 6px 12px;
    font-size: 0.85rem;
    background: color-mix(in srgb, var(--color-border) 65%, transparent);
  }
  .pill.info {
    background: color-mix(in srgb, var(--color-accent) 25%, transparent);
  }
  .pill.success {
    background: color-mix(in srgb, #10b981 30%, transparent);
  }
  .pill.warning {
    background: color-mix(in srgb, #f97316 25%, transparent);
  }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 16px;
  }
  .summary article {
    border: 1px solid var(--color-border);
    border-radius: 16px;
    padding: 16px;
    background: color-mix(in srgb, var(--color-surface) 85%, transparent);
  }
  .summary .count {
    font-size: 2rem;
    margin: 4px 0;
  }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 24px;
  }
  .card-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 16px;
  }
  .card {
    border: 1px solid var(--color-border);
    border-radius: 18px;
    padding: 16px;
    background: color-mix(in srgb, var(--color-surface) 92%, transparent);
    box-shadow: 0 12px 24px -20px rgba(15, 23, 42, 0.45);
  }
  .card__header {
    display: flex;
    justify-content: space-between;
    gap: 8px;
    margin-bottom: 12px;
  }
  dl {
    margin: 0;
    display: grid;
    gap: 4px;
  }
  dt {
    font-weight: 600;
  }
  dd {
    margin: 0;
    color: color-mix(in srgb, var(--color-text) 80%, transparent);
  }
  .muted {
    color: color-mix(in srgb, var(--color-text) 70%, transparent);
    margin: 0;
  }
  .required {
    margin-left: 6px;
    font-size: 0.75rem;
    color: #dc2626;
  }
  .alert {
    border: 1px solid color-mix(in srgb, #f97316 45%, transparent);
    border-radius: 12px;
    padding: 16px;
    background: color-mix(in srgb, #fff7ed 85%, transparent);
  }
  .retry {
    margin-top: 12px;
    border: none;
    background: color-mix(in srgb, var(--color-accent) 35%, transparent);
    color: #fff;
    border-radius: 999px;
    padding: 6px 14px;
    cursor: pointer;
  }
</style>
